name: Test
on:
  push:
    branches:
      - main
      - dev
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu'
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Devops-Grisi-Reyes_shipping-service

  sonarqube-quality-gate:
    name: SonarQube Quality Gate
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Check Quality Gate Status
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        analysis_id=$(curl --location --request GET \
          "https://sonarcloud.io/api/project_analyses/search?project=Devops-Grisi-Reyes_shipping-service&branch=dev" \
          --header "Authorization: Basic ${{ secrets.SONAR_TOKEN }}" \
          --header "Content-Type: application/json" \
          --header "Accept: application/json" \
          | jq -r '.analyses[0].key')
        quality_gate_status=$(curl --location --request GET \
          "https://sonarcloud.io/api/qualitygates/project_status?analysisId=$analysis_id" \
          --header "Authorization: Basic ${{ secrets.SONAR_TOKEN }}" \
          --header "Content-Type: application/json" \
          --header "Accept: application/json" \
          | jq -r '.projectStatus.status')
        echo "SonarQube quality gate status: $quality_gate_status"
